- name: Print IP address
  ansible.builtin.debug:
    var: ansible_default_ipv4.address
    verbosity: 2

- name: Install Pre-Reqs
  apt:
    name:
      - dnsmasq
      - syslinux-common
      - syslinux-efi
      - pxelinux
      - git
    update_cache: true
    state: present

- name: Clone Repo
  shell: |
    if [ -d /srv/tftp ]
    then
      rm -rvf /srv/tftp
    fi
    git clone https://codeberg.org/tookmund/pixie /srv/tftp

- name: Run Setup
  shell: |
    cd /srv/tftp
    ./setup.sh

- name: Install dnsmasq config
  copy:
    src: /srv/tftp/dnsmasq.conf
    remote_src: true
    dest: /etc/dnsmasq.conf

- name: Update dnsmasq.conf with IP
  replace:
    path: /etc/dnsmasq.conf
    regexp: 'X.X.X.X'
    replace: "{{ ansible_default_ipv4.address }}"

- name: Restart dnsmasq
  systemd_service:
    name: dnsmasq
    state: restarted

